packages:
  - 'packages/*'
  - 'apps/docs'
  - 'apps/playground'
  - 'apps/playground/*'
  - 'tools/*'

# 目录排除配置
exclude:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/.turbo/**'

# 共享依赖配置
catalog:
  # 核心依赖
  typescript: ^5.3.0
  vite: ^5.0.0
  vitest: ^1.2.0
  
  # 构建工具
  rollup: ^4.9.0
  esbuild: ^0.19.0
  
  # 开发工具
  eslint: ^8.56.0
  prettier: ^3.2.0
  
  # 框架支持
  vue: ^3.4.0
  react: ^18.2.0
  
  # AST 处理
  gogocode: ^1.0.0
  
  # 工具库
  commander: ^11.1.0
  chalk: ^5.3.0
  ora: ^8.0.0
